# Only turn this on if your asked by the Dev
# Might spam your console and/or chat ;-)
debug: false

# Example configuration
command:
  # Name of the Command.
  command1:
    # Does the Player need to sneak to execute the command?
    # True/False
    requireShift: false
    # Which permission is required to execute this command?
    permission: f-command.example
    # Which command should be executed as the player?
    # You can also use PlaceholderAPI here!
    # Enter without /
    command: say hey try the F key again while pressing shift
    # should the event be canceled?
    cancel: true
    # Should the command be executed from the Server?
    executeAsServer: false

  command2:
    # [num] < [num]
    # [num] <= [num]
    # [num] > [num]
    # [num] >= [num]
    # [num] == [num]
    # [string] equalsignorecase [string]
    # [string] equals [string]
    # advanced
    type: <
    # Under which condition should the command be executed?
    condition1: 1 == 1
    condition2:
    # Which command should be executed as the player?
    # You can also use PlaceholderAPI here!
    # Enter without /
    commandTrue: say Cool, you did it!
    commandFalse:

    # Which permission is required to execute this command?
    permission: f-command.example

    # Should the command be executed from the Server?
    executeAsServer: false


